obj_loss: focal       # "focal" | "bce"
cls_loss: focal      # "focal" | "ce" | "bce"
box_loss: s1          # "s1" | "l1" | "giou" | "diou" | "ciou"
lambda_obj: 2.0
lambda_cls: 0.0
lambda_bbox: 7.0
focal_alpha: 0.25
focal_gamma: 2.0
apply_negative_mining: true