obj_loss: focal       # "focal" | "bce"
cls_loss: focal      # "focal" | "ce" | "bce"
box_loss: hybrid_s1_ciou         # "s1" | "l1" | "giou" | "diou" | "ciou" | "hybrid_s1_ciou" | "hybrid_s1_diou"
lambda_obj: 1.0
lambda_cls: 1.0
lambda_bbox: 5.0
focal_alpha: 0.25
focal_gamma: 1.5
apply_negative_mining: true
obj_neg_weight: 1.0
s1_beta: 0.5
s1_reduction: custom_stride_weighted # "mean" | "sum" | "custom_stride_weighted"
hybrid_xiou_weight: 0.5

stride_weight:
  base: 16.0
  min: 0.75
  max: 3.0