name: yolo
image_size: [512, 512, 3]
backbone_name: resnet18
fpn_channels: 256
returned_layers: [2, 3, 4]
train_backbone: true

nms_threshold: 0.55
score_threshold: 0.5
max_detections: 10

metadata:
  best_model_folder: trained_model