name: yolo
image_size: [300, 300, 3]
backbone_name: resnet18
fpn_channels: 16
returned_layers: [3, 4]
train_backbone: true
use_attention: true

top_k_per_level: 2
center_radius: 1.0
allow_multi_level: true

nms_threshold: 0.5
score_threshold: 0.01
max_detections: 100

metadata:
  best_model_folder: trained_model