name: yolo
image_size: [512, 512, 3]
backbone_name: resnet34
fpn_channels: 384
returned_layers: [1, 2, 3, 4]
train_backbone: true

nms_threshold: 0.35
score_threshold: 0.3
max_detections: 100

metadata:
  best_model_folder: trained_model