name: yolo
image_size: [512, 512, 3]
backbone_name: resnet34
fpn_channels: 384
returned_layers: [1, 2, 3, 4]
train_backbone: true

top_k_per_level: 2
center_radius: 1.0
allow_multi_level: true

nms_threshold: 0.5
score_threshold: 0.01
max_detections: 100

metadata:
  best_model_folder: trained_model